services:
  mock:
    build:
      context: ./src/mock
      dockerfile: Dockerfile
    tty: true
    ports:
      - '4000:4000'
  web:
    build:
      context: ./src/web
      dockerfile: Dockerfile
    env_file:
      - ./src/api/.env.development
    environment:
      NODE_ENV: development
    tty: true
    ports:
      - '8080:8080'
    volumes:
      - ./src/web:/usr/src/web
      - /usr/src/web/node_modules
    depends_on:
      - api
  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    env_file:
      - ./src/api/.env.development
    environment:
      NODE_ENV: development
      DB_HOST: db
      MAIL_HOST: 'host.docker.internal'
      TS_NODE_HISTORY: '/tmp/.ts_node_repl_history'
      DIVISIONSJSON: 'http://mock:4000/divisions'
      EMPLOYEEJSON: 'http://mock:4000/employees'
      EMPLOYEEDETAILJSON: 'http://mock:4000/employeedetail'
    tty: true
    ports:
      - '3000:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - 'host.docker.internal:172.17.0.1'
    volumes:
      - ./src/api:/usr/src/api
      - /usr/src/api/node_modules
    depends_on:
      - mock
